### ISSUE TITLE
Sitting teleports you somewhere else

### ISSUE THREAD

**Issue by felix104116** [Xerasin/Sit-Anywhere#1]
Hi!

I'm actually having a problem with the Sit Everywhere addon, when i try to sit by pressing : ALT + E
it teleports me somewhere else near there. It only works when i try to sit in the middle of a seat and wont work on a chair, it teleports me beside it.

Thanks a lot!

**Comment by LUModder** [comment]
Could you give a video example?

**Comment by Xerasin** [comment]
Issue is 5 years old, closing as no relevant information has been given since then and issue is likely not applicable anymore.
