### ISSUE TITLE
Spawning un-deletable chairs

### ISSUE THREAD

**Issue by buffet-time** [Xerasin/Sit-Anywhere#11]
ya, as many others on steam and here have stated, you really need to fix this.

**Comment by alotlikebirds** [comment]
I am also having this issue!

**Comment by LuaTenshi** [comment]
I can't seem to replicate your issue... What gamemode are you running? What other addons do you have?

**Comment by Xerasin** [comment]
Issue is 4 years old, closing as no relevant information has been given since then and issue is likely not applicable anymore.
