### ISSUE TITLE
Mod Doesn't Work in Cinema Gamemode..

### ISSUE THREAD

**Issue by AbominationOfficial** [Xerasin/Sit-Anywhere#12]
The Sit Anywhere mod doesn't work on my server in the Cinema gamemode. At first, I thought it was my server not downloading it right or something, but with what I've seen it might be because of Cinema. Is there any fix to this and, if not, could you please fix it..?

**Comment by Chiller252** [comment]
I was just about to post about this too. I know it's cinema because I was able to get it working in the sandbox gamemode on the same map. I posted on the Cinema discussion as well.

**Comment by Chillstice** [comment]
Seems to be working now, don't know why. pls close
