### ISSUE TITLE
Improper CPPI Ownership from latest pull request

### ISSUE THREAD

**Issue by Mista-Tea** [Xerasin/Sit-Anywhere#15]
Hello!

The latest merged [pull request](https://github.com/Xerasin/Sit-Anywhere/commit/fa7f1a12c564e3cbe987a33ff0391083b4f94bcb) from @thegrb93 adds the [following](https://github.com/Xerasin/Sit-Anywhere/blob/f4283bb0032be7c20d8b15814d9b1bc18b530802/lua/autorun/server/Sit.lua#L47-L49) to Server/Sit.lua lines 47-49: 

```lua
if CPPI then
	vehicle:CPPISetOwner(Entity(0))
end
```

In other words, assign the owner of the vehicle to the world entity.

This is undefined behavior and is breaking my CPPI implementation, which abides by the following rules as stated in [v1.3](http://ulyssesmod.net/archive/CPPI_v1-3.pdf):

```
Function: CPPISetOwner( [Player] ply ) - Required
1. Sets a new owner for this entity.
2. Returns true on success, false on failure.
3. ply will be a Player entity or nil (do error checking regardless).
4. If ply is nil, ownership should be cleared for the entity.
5. ONLY defined on the server.
```

In particular, the entity passed should **only** be a player entity or nil. Not some non-player entity like the world entity.

Please feel free to correct me if I'm wrong. However, from my administration module's point of view, it should either be setting the owner to the actual player, or more appropriately, not setting it at all (or whatever the previous behavior was).

**Comment by thegrb93** [comment]
Hm weird rules. how do you make the entity unownable then? I thought nil would clear the owner and leave it up for grabs while NULL would set the entity to be owned by world. NADMOD prop protection uses NULL to make the world own the entity and nil doesn't do anything.
