### ISSUE TITLE
Still can't stand up

### ISSUE THREAD

**Issue by Kapsulon** [Xerasin/Sit-Anywhere#35]
Sorry that the errors had nothing to do with this addon but we still can't stand up, you can look at the older issue, someone said you still couldn't stand up aswell, i got this error that time:

`Timer Failed! [Simple][@addons/sit/lua/autorun/server/sit.lua (line 605)]`

**Comment by Kapsulon** [comment]
I think this addon have a timer similar as pvault ?

**Comment by Xerasin** [comment]
That error is from an older version of the script. There is no timer on that line, please make sure you are up to date before posting an issue.
