### ISSUE TITLE
Assertion Failed? Non critical Error

### ISSUE THREAD

**Issue by LucianDevran** [Xerasin/Sit-Anywhere#39]
Hey im using this addon in a collection but the server fails to download the addon i think, this happens on 2 different host systems btw, 

Processing addon 350: The Sit Anywhere Script! (108176967)...
Addon needs downloading...
tcpconnection.cpp (1020) : Assertion Failed: CTCPConnection::BInternalAsyncConnect - trying to bind to an IPv4 address but k_uNetFlagAllowIPv6 is set
tcpconnection.cpp (1020) : Assertion Failed: CTCPConnection::BInternalAsyncConnect - trying to bind to an IPv4 address but k_uNetFlagAllowIPv6 is set
Uploading dump (in-process) [proxy '']
/tmp/dumps/crash_20200621182639_18.dmp
success = yes
response:  Discarded=1
tcpconnection.cpp (1020) : Assertion Failed: CTCPConnection::BInternalAsyncConnect - trying to bind to an IPv4 address but k_uNetFlagAllowIPv6 is set
tcpconnection.cpp (1020) : Assertion Failed: CTCPConnection::BInternalAsyncConnect - trying to bind to an IPv4 address but k_uNetFlagAllowIPv6 is set
tcpconnection.cpp (1020) : Assertion Failed: CTCPConnection::BInternalAsyncConnect - trying to bind to an IPv4 address but k_uNetFlagAllowIPv6 is set
tcpconnection.cpp (1020) : Assertion Failed: CTCPConnection::BInternalAsyncConnect - trying to bind to an IPv4 address but k_uNetFlagAllowIPv6 is set
tcpconnection.cpp (1020) : Assertion Failed: CTCPConnection::BInternalAsyncConnect - trying to bind to an IPv4 address but k_uNetFlagAllowIPv6 is set
tcpconnection.cpp (1020) : Assertion Failed: CTCPConnection::BInternalAsyncConnect - trying to bind to an IPv4 address but k_uNetFlagAllowIPv6 is set
Downloaded!
Mounted!

https://pastebin.com/3n2xeA1Z
Full server log

Edit the Addon is installed successfully idk what that is, so i will let you know anyways

**Comment by Xerasin** [comment]
This is a bug with garry's mod not my script.
