### ISSUE TITLE
wrong eyeangles when sitting on the flat large and edge of the map

### ISSUE THREAD

**Issue by dounai2333** [Xerasin/Sit-Anywhere#44]
current if you sit with an pretty large and flat edge site, the eyeangles of the invisible vehicle is offset 60(or 75) Y eye angle to the right.
it normally won't happen if the edge isn't 100% flat or isn't large, so that's why i'm saying it, and a weird thing is it also won't happen if the target's Y eye angle is 0 (north if you want to call that)

(test from 180 y angle)
![`AGOIGRZ_1 }2TILI(GI _K](https://user-images.githubusercontent.com/45044404/129708986-3fdd8c76-a634-4f07-a371-0e8b35b25690.png)

tested multi times and confirmed it's not a rare bug or conflict by other addons, you can trigger it easily on the almost every maps (or a large props), i tried to look at the codes and want to find where is the problem, but i didn't make it, can you fix it?

**Comment by Xerasin** [comment]
Having trouble replicating this, it sits at my eye angle even in the same place you did it, BUT you can hold ALT+E and an arrow will appear that lets you pick any angle you wish to sit at.

**Comment by Xerasin** [comment]
I think I figured out the issue, tell me if that commit helps..

The area profiler only took samples every 15 degrees, code was checking if eye angles was within 5 of that, so there was 5 degree area between each sample that could of invalidating everything so it just took the lowest cost which is the first in that scenario.

**Comment by dounai2333** [comment]
nope, the issue is still exists and it even start to offset Y angle to the left now (and same with 60/75), i have found a friend to do the test with me and he got the same result (not in the correct eye angles)
i do normally press a key since i have bound command "sit", and i'm thinking if that causing problem but not, tested with ALE+E and still easily to re-trigger the same bug

> you can hold ALT+E and an arrow will appear that lets you pick any angle you wish to sit at.

yea this one works great without any affect, maybe it's the time to use this now :o



the proof game are using latest lua from github:
![O{_(5A U NV@X$@BVCRQPHA](https://user-images.githubusercontent.com/45044404/131244277-0a4723d5-96a1-4b76-8677-71ed70eaf371.png)

and with the same position after executed test code:
![SJ7UZJI%$(IX}MT48Z}LI21](https://user-images.githubusercontent.com/45044404/131244539-db468a4a-b44b-47d7-bbdb-6cccf9e9fe16.png)

everything back to normal, but it doesn't always offset 60 (sometime 75) so it's pretty hard to locate the problem code

**Comment by Xerasin** [comment]
Are you sitting like one or two?

1
![EllipticalUnusedPrizeBaleenwhale 1](https://user-images.githubusercontent.com/1499878/131259970-18b5536e-5ecb-4f6a-a187-60fc368116a8.png)

2
![SpeedyFirmFarawayTilefish 1](https://user-images.githubusercontent.com/1499878/131259974-5151ecf8-b68a-4b8a-8760-30ef4a1ee7e6.png)

The intended way to sit in this scenario is one, because the script expects the sit surface to be in front of you. For situations like two it's best to use the arrow. Btw, you can also bind +sit instead of sit to get the same arrow functionality.

**Comment by dounai2333** [comment]
wut, i always do 2 instead, okay i know why it are having issue with me now, i think their results are the same, thanks for the answer and trying to fix the bug, the problem stems from the way i used lol
