### ISSUE TITLE
addon doesnt work

### ISSUE THREAD

**Issue by HerosYellow** [Xerasin/Sit-Anywhere#46]
i tryed these combinations;
w (walk) + e (use)
w (walk) + e (use) + alt
alt + e (use)

but addon does not sit

**Comment by Xerasin** [comment]
Unless your key config is completely nuts and walk is actually bound to w, `Walk (Move Slowly)` not `Move Forward`. Make sure alt is bound to `Walk (Move Slowly)` this is in the options under the Miscellaneous Movement.
