### ISSUE TITLE
Crash when sitting down on prop_physics with brush model

### ISSUE THREAD

**Issue by Kurome76** [Xerasin/Sit-Anywhere#49]
Done by picking the model from some brush entity (like a func_door) with the model manipulator, applying that to a physics prop and pasting it in with a duplicator. 

When sat down on it, crashes game and puts this in the crashlog (x64 build)

  Server
    0. EnterVehicle - [C]:-1
      1. Sit - lua/sitanywhere/server/sit.lua:154
        2. sitcmd - lua/sitanywhere/server/sit.lua:500
          3. (null) - lua/sitanywhere/server/sit.lua:508
            4. (null) - lua/includes/modules/concommand.lua:54

**Comment by Xerasin** [comment]
This should be fixed now I hope, btw I recommend moving your bind to +sit NOT sit. Using +sit allows you to select the angle you wish to sit at as if you were holding ALT+E.
