### ISSUE TITLE
Sit doesn't allow the damage ConVar or something?

### ISSUE THREAD

**Issue by DiablosGamer** [Xerasin/Sit-Anywhere#9]
Hi! Sorry for disturbing you, but I leave a comment in your profile (Xerarose) and no request answer since 2 weeks..
So, I've a problem! When player sit down, he doesn't take damage. I tried to change the value of the "sitting_can_damage_players_sitting" ConVar, to shoot player when he is sit and I am stand,... When I sit and him too, doesn't work... NOTHING WORKS ! I looked at the code and I don't know what is logic (Change Collision Group when the ConVar has the value "1" ? Whut?)... But I know that many people can take damage when they are sit. So why me?
Please help.
Thanks!

**Comment by gauthierplus** [comment]
https://mtxserv.com/forums/threads/pouvoir-etre-inflige-de-degats-et-sortir-une-arme-en-etant-assis.1089/

If you want with this little script + the sit anywhere you can receive damages and use your weapons.

**Comment by Xerasin** [comment]
The sitting_can_damage_players_sitting convar is hacky at best, don't expect it to ever really work out well. 

Also, please do not links to outdated versions of the script. Let alone a version that literally just changed the DEFAULT value of the convar.
